# Generated by Django 4.0.1 on 2022-01-05 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ansible', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostgroup',
            name='hostname',
        ),
        migrations.AddField(
            model_name='hostgroup',
            name='hostname',
            field=models.ManyToManyField(to='ansible.Host'),
        ),
    ]
