# Generated by Django 4.0.1 on 2022-01-05 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ansible', '0002_remove_hostgroup_hostname_hostgroup_hostname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostgroup',
            old_name='hostname',
            new_name='host',
        ),
    ]
