# Generated by Django 4.0 on 2022-01-06 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ansible', '0003_rename_hostname_hostgroup_host'),
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script_name', models.CharField(max_length=100)),
                ('text', models.TextField()),
            ],
        ),
    ]
