# Generated by Django 4.0 on 2022-01-06 07:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ansible', '0004_script'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='pub_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
