# Generated by Django 4.0 on 2022-01-06 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ansible', '0005_script_pub_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='description',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
