# Generated by Django 4.0.1 on 2022-01-07 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ansible', '0006_script_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('account', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=200)),
                ('privilege', models.ManyToManyField(to='ansible.Host')),
            ],
        ),
    ]
