# Generated by Django 4.0.1 on 2022-01-10 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ansible', '0008_alter_user_privilege'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
